# Profile information
name: Marco
title: Marco
description: > # this means to ignore newlines until "baseurl:"
  This is devops blog.
permalink: ':title/'
baseurl: "/Marco" # the subpath of your site, e.g. /blog
url: "https://fannl.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: #Add your Github

# Contact form
email: #your-email@domain.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - 
  - 
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
